const WEBHOOK='https://hook.eu2.make.com/9otc8coig6ulfw6eeqt8oraph8rhi4y1';
const els={rassell:document.getElementById('rassellTasks'),michelle:document.getElementById('michelleTasks')};
const message=document.getElementById('message'),dialog=document.getElementById('pinDialog'),pinForm=document.getElementById('pinForm'),pin=document.getElementById('pin');
let pending=null;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function taskHtml(t,child){return `<article class="task"><div><div class="task-name">${escapeHtml(t.title)}</div><small>+${Number(t.points||0)} points</small></div><button class="reset" type="button" data-task-id="${escapeHtml(t.id)}" data-child="${child}">Reset</button></article>`;}
function render(data){let count=0;for(const child of ['rassell','michelle']){const items=data.children?.[child]?.completedTasks||[];count+=items.length;els[child].innerHTML=items.length?items.map(t=>taskHtml(t,child==='rassell'?'Rassell':'Michelle')).join(''):'<div class="empty">No completed tasks</div>';}document.getElementById('completedCount').textContent=count;document.getElementById('updated').textContent=data.updatedAt?new Date(data.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';}
async function load(){try{const r=await fetch(`latest.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Could not load dashboard');render(await r.json());message.textContent='';}catch(e){message.textContent=e.message;message.className='message error';}}
document.addEventListener('click',e=>{const b=e.target.closest('button.reset');if(!b)return;pending={button:b,taskId:b.dataset.taskId,child:b.dataset.child};pin.value='';dialog.showModal();setTimeout(()=>pin.focus(),50);});
pinForm.addEventListener('submit',async e=>{e.preventDefault();if(!pending)return;if(!/^\d{6}$/.test(pin.value)){pin.setCustomValidity('Enter the six-digit parent code');pin.reportValidity();return;}pin.setCustomValidity('');dialog.close();const {button,taskId,child}=pending;button.disabled=true;button.textContent='Resetting…';message.textContent='';try{const r=await fetch(WEBHOOK,{method:'POST',body:new URLSearchParams({taskId,child,pin:pin.value})});if(!r.ok)throw new Error('Reset failed');const data=await r.json();render(data);message.textContent='Task reopened and points reversed.';message.className='message success';}catch(err){button.disabled=false;button.textContent='Reset';message.textContent='Reset failed. Check the parent code and try again.';message.className='message error';}finally{pending=null;}});
load();setInterval(load,60000);